version: '3.4'
networks:
  dev:
    driver: bridge
services:
  healthcare:
    image: healthcareapi
    depends_on:
     - "app_db"
    container_name: healthcare-service
    ports:
      - "8000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID =postgres;Password=postgres;Server=app_db;Port=5432;Database=SampleDriverDb; Integrated Security=true;Pooling=true;
    networks:
      - dev
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SampleDriverDb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  app_data: